//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _948948849
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisan
    {
        public byte ID { get; set; }
        public string AdSoyad { get; set; }
        public string TC { get; set; }
        public string TelNo { get; set; }
        public string Unvan { get; set; }
        public string Sifre { get; set; }
        public string Cinsiyet { get; set; }
        public string DogumTarih { get; set; }
        public Nullable<int> Maas { get; set; }
    }
}
