//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _948948849
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public string TC { get; set; }
        public string TelNo { get; set; }
        public string Unvanı { get; set; }
        public string Şifre { get; set; }
        public string Cinsiyet { get; set; }
        public string DogumTarihi { get; set; }
        public string Maas { get; set; }
    }
}
