//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _948948849
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSPARİS
    {
        public byte ID { get; set; }
        public string MUSTERIADSOYAD { get; set; }
        public string MUSTRİADRES { get; set; }
        public string PİZZASECİMİ { get; set; }
        public string PİZZABOYUTU { get; set; }
        public string PİZZASAYISI { get; set; }
        public string İCECEK { get; set; }
        public string İCECEKSAYISI { get; set; }
        public string EXTRAMALZEME { get; set; }
        public Nullable<int> TUTAR { get; set; }
        public string TARİH { get; set; }
        public string TELEFON { get; set; }
        public string KENARSECİMİ { get; set; }
    }
}
